## Building pandas Series and DataFrames

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
from openbb import obb

In [2]:
obb.user.preferences.output_type = "dataframe"

Generates a date range with second frequency starting from 2016-01-01 for 100 periods and displays it

In [3]:
seconds = pd.date_range("2016-01-01", periods=100, freq="s")

In [4]:
display(seconds)

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 00:00:01',
               '2016-01-01 00:00:02', '2016-01-01 00:00:03',
               '2016-01-01 00:00:04', '2016-01-01 00:00:05',
               '2016-01-01 00:00:06', '2016-01-01 00:00:07',
               '2016-01-01 00:00:08', '2016-01-01 00:00:09',
               '2016-01-01 00:00:10', '2016-01-01 00:00:11',
               '2016-01-01 00:00:12', '2016-01-01 00:00:13',
               '2016-01-01 00:00:14', '2016-01-01 00:00:15',
               '2016-01-01 00:00:16', '2016-01-01 00:00:17',
               '2016-01-01 00:00:18', '2016-01-01 00:00:19',
               '2016-01-01 00:00:20', '2016-01-01 00:00:21',
               '2016-01-01 00:00:22', '2016-01-01 00:00:23',
               '2016-01-01 00:00:24', '2016-01-01 00:00:25',
               '2016-01-01 00:00:26', '2016-01-01 00:00:27',
               '2016-01-01 00:00:28', '2016-01-01 00:00:29',
               '2016-01-01 00:00:30', '2016-01-01 00:00:31',
               '2016-01-01 00:00:32', '2016-01-01 00:00:33',
               '2016-01-01 00:00:34', '2016-01-01 00:00:35',
               '2016-01-01 00:00:36', '2016-01-01 00:00:37',
               '2016-01-01 00:00:38', '2016-01-01 00:00:39',
               '2016-01-01 00:00:40', '2016-01-01 00:00:41',
               '2016-01-01 00:00:42', '2016-01-01 00:00:43',
               '2016-01-01 00:00:44', '2016-01-01 00:00:45',
               '2016-01-01 00:00:46', '2016-01-01 00:00:47',
               '2016-01-01 00:00:48', '2016-01-01 00:00:49',
               '2016-01-01 00:00:50', '2016-01-01 00:00:51',
               '2016-01-01 00:00:52', '2016-01-01 00:00:53',
               '2016-01-01 00:00:54', '2016-01-01 00:00:55',
               '2016-01-01 00:00:56', '2016-01-01 00:00:57',
               '2016-01-01 00:00:58', '2016-01-01 00:00:59',
               '2016-01-01 00:01:00', '2016-01-01 00:01:01',
               '2016-01-01 00:01:02', '2016-01-01 00:01:03',
               '2016-01-01 00:01:04', '2016-01-01 00:01:05',
               '2016-01-01 00:01:06', '2016-01-01 00:01:07',
               '2016-01-01 00:01:08', '2016-01-01 00:01:09',
               '2016-01-01 00:01:10', '2016-01-01 00:01:11',
               '2016-01-01 00:01:12', '2016-01-01 00:01:13',
               '2016-01-01 00:01:14', '2016-01-01 00:01:15',
               '2016-01-01 00:01:16', '2016-01-01 00:01:17',
               '2016-01-01 00:01:18', '2016-01-01 00:01:19',
               '2016-01-01 00:01:20', '2016-01-01 00:01:21',
               '2016-01-01 00:01:22', '2016-01-01 00:01:23',
               '2016-01-01 00:01:24', '2016-01-01 00:01:25',
               '2016-01-01 00:01:26', '2016-01-01 00:01:27',
               '2016-01-01 00:01:28', '2016-01-01 00:01:29',
               '2016-01-01 00:01:30', '2016-01-01 00:01:31',
               '2016-01-01 00:01:32', '2016-01-01 00:01:33',
               '2016-01-01 00:01:34', '2016-01-01 00:01:35',
               '2016-01-01 00:01:36', '2016-01-01 00:01:37',
               '2016-01-01 00:01:38', '2016-01-01 00:01:39'],
              dtype='datetime64[ns]', freq='s')

Defines a function 'rnd' that returns an array of 100 random numbers

In [5]:
def rnd():
    return np.random.randn(
        100,
    )

Creates three pandas Series with random data and the previously generated seconds as index

In [6]:
s_1 = pd.Series(rnd(), index=seconds)
s_2 = pd.Series(rnd(), index=seconds)
s_3 = pd.Series(rnd(), index=seconds)

Creates a DataFrame 'df' from the three Series and displays it

In [7]:
df = pd.DataFrame({"a": s_1, "b": s_2, "c": s_3})

In [8]:
display(df)

                            a         b         c
2016-01-01 00:00:00  0.766271 -1.309263 -0.372513
2016-01-01 00:00:01  0.568159 -0.126168  0.352806
2016-01-01 00:00:02  1.293436 -0.143443  1.584063
2016-01-01 00:00:03 -1.793370  0.662279  0.158518
2016-01-01 00:00:04 -1.093767 -1.855861  0.573109
...                       ...       ...       ...
2016-01-01 00:01:35 -0.383279 -0.222609 -0.767720
2016-01-01 00:01:36 -0.482125  1.807752 -0.006487
2016-01-01 00:01:37 -0.569352  1.397487 -1.684161
2016-01-01 00:01:38  0.115788 -0.025850 -1.151523
2016-01-01 00:01:39 -0.619982  0.079096 -0.912934

[100 rows x 3 columns]

Creates a list of tuples with date and symbol

In [9]:
tuples = [
    (pd.Timestamp("2023-07-10"), "WMT"),
    (pd.Timestamp("2023-07-10"), "JPM"),
    (pd.Timestamp("2023-07-10"), "TGT"),
    (pd.Timestamp("2023-07-11"), "WMT"),
    (pd.Timestamp("2023-07-11"), "JPM"),
    (pd.Timestamp("2023-07-11"), "TGT"),
]
midx = pd.MultiIndex.from_tuples(tuples, names=("date", "symbol"))

In [10]:
display(tuples)

[(Timestamp('2023-07-10 00:00:00'), 'WMT'),
 (Timestamp('2023-07-10 00:00:00'), 'JPM'),
 (Timestamp('2023-07-10 00:00:00'), 'TGT'),
 (Timestamp('2023-07-11 00:00:00'), 'WMT'),
 (Timestamp('2023-07-11 00:00:00'), 'JPM'),
 (Timestamp('2023-07-11 00:00:00'), 'TGT')]

Creates a MultiIndex from the list of tuples and assigns it to the index of a new DataFrame 'df'

In [11]:
df = pd.DataFrame(
    {
        "close": [158.11, 144.64, 132.55, 158.20, 146.61, 134.86],
        "factor_1": [0.31, 0.24, 0.67, 0.29, 0.23, 0.71],
    },
    index=midx,
)

In [12]:
display(df)

                    close  factor_1
date       symbol
2023-07-10 WMT     158.11      0.31
           JPM     144.64      0.24
           TGT     132.55      0.67
2023-07-11 WMT     158.20      0.29
           JPM     146.61      0.23
           TGT     134.86      0.71

Fetches options chains for the symbol "SPY" using the "cboe" provider and stores it in 'chains'

In [15]:
# chains = obb.derivatives.options.chains("SPY", provider="cboe")
chains = obb.derivatives.options.chains("SPY", provider="yfinance")

In [16]:
display(chains)

,underlying_symbol,underlying_price,contract_symbol,expiration,dte,strike,option_type,open_interest,volume,last_trade_price,last_trade_time,bid,ask,change,change_percent,implied_volatility,in_the_money,currency
0,SPY,598.97,SPY250203P00410000,2025-02-03,1,410.0,put,50,100,0.01,2025-01-31 10:37:39-05:00,0.00,0.01,0.00,0.000000,1.531252,False,USD
1,SPY,598.97,SPY250203P00415000,2025-02-03,1,415.0,put,30,26,0.01,2025-01-27 15:27:57-05:00,0.00,0.01,0.00,0.000000,1.500002,False,USD
2,SPY,598.97,SPY250203P00435000,2025-02-03,1,435.0,put,95,5,0.01,2025-01-28 09:46:11-05:00,0.00,0.01,0.00,0.000000,1.312503,False,USD
3,SPY,598.97,SPY250203P00440000,2025-02-03,1,440.0,put,239,103,0.01,2025-01-28 15:32:26-05:00,0.00,0.01,0.00,0.000000,1.250004,False,USD
4,SPY,598.97,SPY250203P00445000,2025-02-03,1,445.0,put,59,59,0.02,2025-01-23 14:27:23-05:00,0.00,0.01,0.00,0.000000,1.218754,False,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,SPY,598.97,SPY271217C00890000,2027-12-17,1048,890.0,call,3,4,4.47,2025-01-15 11:24:58-05:00,5.38,6.69,0.00,0.000000,0.160546,False,USD
6720,SPY,598.97,SPY271217C00895000,2027-12-17,1048,895.0,call,6,1,6.00,2025-01-31 14:51:44-05:00,5.07,6.35,-0.08,-0.013158,0.160210,False,USD
6721,SPY,598.97,SPY271217C00900000,2027-12-17,1048,900.0,call,1732,360,5.60,2025-01-31 14:53:39-05:00,5.00,6.02,-0.20,-0.034483,0.159844,False,USD
6722,SPY,598.97,SPY271217P00900000,2027-12-17,1048,900.0,put,0,2,302.30,2025-01-27 11:22:54-05:00,296.00,300.75,0.00,0.000000,0.136544,True,USD
6723,SPY,598.97,SPY271217C00905000,2027-12-17,1048,905.0,call,36,9,5.30,2025-01-30 11:37:32-05:00,4.85,5.72,0.00,0.000000,0.159585,False,USD

Sets a MultiIndex on the 'chains' DataFrame using the columns 'expiration', 'strike', and 'option_type' and displays it

In [17]:
df = chains.set_index(["expiration", "strike", "option_type"])

In [18]:
display(df)

                              underlying_symbol  underlying_price  \
expiration strike option_type
2025-02-03 410.0  put                       SPY            598.97
           415.0  put                       SPY            598.97
           435.0  put                       SPY            598.97
           440.0  put                       SPY            598.97
           445.0  put                       SPY            598.97
...                                         ...               ...
2027-12-17 890.0  call                      SPY            598.97
           895.0  call                      SPY            598.97
           900.0  call                      SPY            598.97
                  put                       SPY            598.97
           905.0  call                      SPY            598.97

                                  contract_symbol   dte  open_interest  \
expiration strike option_type
2025-02-03 410.0  put          SPY250203P00410000     1             50
           415.0  put          SPY250203P00415000     1             30
           435.0  put          SPY250203P00435000     1             95
           440.0  put          SPY250203P00440000     1            239
           445.0  put          SPY250203P00445000     1             59
...                                           ...   ...            ...
2027-12-17 890.0  call         SPY271217C00890000  1048              3
           895.0  call         SPY271217C00895000  1048              6
           900.0  call         SPY271217C00900000  1048           1732
                  put          SPY271217P00900000  1048              0
           905.0  call         SPY271217C00905000  1048             36

                               volume  last_trade_price  \
expiration strike option_type
2025-02-03 410.0  put             100              0.01
           415.0  put              26              0.01
           435.0  put               5              0.01
           440.0  put             103              0.01
           445.0  put              59              0.02
...                               ...               ...
2027-12-17 890.0  call              4              4.47
           895.0  call              1              6.00
           900.0  call            360              5.60
                  put               2            302.30
           905.0  call              9              5.30

                                        last_trade_time     bid     ask  \
expiration strike option_type
2025-02-03 410.0  put         2025-01-31 10:37:39-05:00    0.00    0.01
           415.0  put         2025-01-27 15:27:57-05:00    0.00    0.01
           435.0  put         2025-01-28 09:46:11-05:00    0.00    0.01
           440.0  put         2025-01-28 15:32:26-05:00    0.00    0.01
           445.0  put         2025-01-23 14:27:23-05:00    0.00    0.01
...                                                 ...     ...     ...
2027-12-17 890.0  call        2025-01-15 11:24:58-05:00    5.38    6.69
           895.0  call        2025-01-31 14:51:44-05:00    5.07    6.35
           900.0  call        2025-01-31 14:53:39-05:00    5.00    6.02
                  put         2025-01-27 11:22:54-05:00  296.00  300.75
           905.0  call        2025-01-30 11:37:32-05:00    4.85    5.72

                               change  change_percent  implied_volatility  \
expiration strike option_type
2025-02-03 410.0  put            0.00        0.000000            1.531252
           415.0  put            0.00        0.000000            1.500002
           435.0  put            0.00        0.000000            1.312503
           440.0  put            0.00        0.000000            1.250004
           445.0  put            0.00        0.000000            1.218754
...                               ...             ...                 ...
2027-12-17 890.0  call           0.00        0.000000            0.160546
           895.0  call          -0.08       -0.013158            0.160210
           900.0  call          -0.20       -0.034483            0.159844
                  put            0.00        0.000000            0.136544
           905.0  call           0.00        0.000000            0.159585

                               in_the_money currency
expiration strike option_type
2025-02-03 410.0  put                 False      USD
           415.0  put                 False      USD
           435.0  put                 False      USD
           440.0  put                 False      USD
           445.0  put                 False      USD
...                                     ...      ...
2027-12-17 890.0  call                False      USD
           895.0  call                False      USD
           900.0  call                False      USD
                  put                  True      USD
           905.0  call                False      USD

[6724 rows x 15 columns]

**Jason Strimpel** is the founder of <a href='https://pyquantnews.com/'>PyQuant News</a> and co-founder of <a href='https://www.tradeblotter.io/'>Trade Blotter</a>. His career in algorithmic trading spans 20+ years. He previously traded for a Chicago-based hedge fund, was a risk manager at JPMorgan, and managed production risk technology for an energy derivatives trading firm in London. In Singapore, he served as APAC CIO for an agricultural trading firm and built the data science team for a global metals trading firm. Jason holds degrees in Finance and Economics and a Master's in Quantitative Finance from the Illinois Institute of Technology. His career spans America, Europe, and Asia. He shares his expertise through the <a href='https://pyquantnews.com/subscribe-to-the-pyquant-newsletter/'>PyQuant Newsletter</a>, social media, and has taught over 1,000+ algorithmic trading with Python in his popular course **<a href='https://gettingstartedwithpythonforquantfinance.com/'>Getting Started With Python for Quant Finance</a>**. All code is for educational purposes only. Nothing provided here is financial advise. Use at your own risk.